spring:
  cloud:
    gateway:
      routes:
        - id: test_route1
          uri: https://www.bilibili.com
          predicates:
            - Query=url,bili
        - id: test_route2
          uri: https://www.qq.com
          predicates:
            - Query=url,qq